version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  search-service:
    container_name: search-service
    build: ./search-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    entrypoint: /bin/sh
    command: >
      -c "
      while ! (nc -z mongodb 27017); do sleep 5; echo 'Waiting for mongodb to start-up...'; done;
      java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar -Dspring.profiles.active=docker /app.jar
      "
